services:
  app:
    build:
      context: .
    container_name: gatxel_go_app
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres  
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      MIGRATION_PATH: /app/migration
    ports:
      - "${PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy  
    volumes:
      - ./migration:/app/migration
    networks:
      - gatxel_go_network

  postgres:
    image: postgres:15
    container_name: gatxel_go_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration:/app/migration   
    networks:
      - gatxel_go_network
    healthcheck:   
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  gatxel_go_network:
    driver: bridge